name: Hexo Deploy

on:
  push:
    branches:
      - main  # 你可以指定你要监听的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Clean hexo
        run: npx hexo clean

      - name: Generate hexo
        run: npx hexo generate

      - name: Deploy hexo
        run: npx hexo deploy
        env:
          # 在这里使用你的 GitHub Token 或其他必要的环境变量
          DEPLOY_REPO: github.com/San-sin-sun/San-sin-sun.github.io.git
          DEPLOY_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}